name: Build OpenWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: debian

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq clean
        sudo -E apt-get install -y vim iputils-ping curl make openssh-server iproute2 build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        git reset --hard v23.05.3
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Patch source code
      run: |
        cp 0001-Add-support-to-Xiaomi-AX3000T.patch openwrt/
        cd openwrt
        git apply --check 0001-Add-support-to-Xiaomi-AX3000T.patch
        git apply 0001-Add-support-to-Xiaomi-AX3000T.patch

    - name: Load feeds configuration
      run: |
        cd openwrt
        cp feeds.conf.default feeds.conf

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: Install feeds
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Load configuration
      run: cp xiaomi_mi-router-ax3000t-stock.config openwrt/.config

    - name: Download package
      id: package
      run: |
        cd openwrt
        make -j$(nproc) download

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        mkdir $GITHUB_WORKSPACE/build
        cp bin/targets/mediatek/filogic/*.ubi bin/targets/mediatek/filogic/*.bin $GITHUB_WORKSPACE/build/

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_bin
        path: build/
